import React from 'react'

export const loginStyles: Record<string, React.CSSProperties> = {
  page: {
    minHeight: '100vh',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    background: 'var(--bg-base)',
    position: 'relative',
    overflow: 'hidden',
    padding: '20px',
  },
  blobViolet: {
    position: 'absolute',
    top: '-150px', left: '-150px',
    width: '600px', height: '600px', borderRadius: '50%',
    background: 'radial-gradient(circle, rgba(159,103,255,0.15) 0%, transparent 70%)',
    pointerEvents: 'none',
  },
  blobPlum: {
    position: 'absolute',
    bottom: '-150px', right: '-150px',
    width: '500px', height: '500px', borderRadius: '50%',
    background: 'radial-gradient(circle, rgba(124,58,237,0.2) 0%, transparent 70%)',
    pointerEvents: 'none',
  },
  card: {
    background: 'var(--bg-card)',
    border: '1px solid var(--border)',
    borderRadius: 'var(--r-xl)',
    padding: '40px',
    width: '100%',
    maxWidth: '440px',
    boxShadow: 'var(--shadow-card)',
    position: 'relative',
    zIndex: 1,
  },
  heading: {
    fontSize: '22px',
    fontWeight: 800,
    color: 'var(--text-primary)',
    letterSpacing: '-0.5px',
    marginBottom: '6px',
  },
  subheading: {
    fontSize: '13px',
    color: 'var(--text-secondary)',
    marginBottom: '28px',
  },
  formGroup: {
    marginBottom: '20px',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    width: '100%',
  },
  label: {
    display: 'block',
    width: '100%',
    fontSize: '12px',
    fontWeight: 700,
    color: 'var(--text-secondary)',
    marginBottom: '8px',
    textTransform: 'uppercase',
    letterSpacing: '0.6px',
    textAlign: 'left',
  },
  input: {
    display: 'block',
    width: '100%',
    boxSizing: 'border-box',
    background: 'var(--bg-elevated)',
    border: '1px solid var(--border)',
    borderRadius: 'var(--r-md)',
    padding: '12px 16px',
    color: 'var(--text-primary)',
    fontFamily: 'var(--font)',
    fontSize: '14px',
    outline: 'none',
  },
  submitBtn: {
    width: '100%',
    justifyContent: 'center',
    marginTop: '16px',
    height: '46px',
    fontSize: '14px',
    fontWeight: 700,
  },
  footnote: {
    fontSize: '11px',
    color: 'var(--text-muted)',
    textAlign: 'center',
    marginTop: '24px',
  },
}
